import Head from "next/head";
import { AboutSection } from "./components";
import { MainWrapper } from "./layout";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Steven Strongest - Web develop</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/avatar.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,300;0,500;0,700;0,900;1,300;1,500&display=swap"
          rel="stylesheet"
        />
      </Head>
      <MainWrapper>
        <AboutSection />

        <div className="section">
          <h1>Section 2</h1>
        </div>

        <div className="section">
          <h1>Section 3</h1>
        </div>
      </MainWrapper>
    </div>
  );
}
